name: "🚀 release"

on:
    push:
        branches:
          - main

jobs:
    release:
        name: 🚀 Public npm
        runs-on: ubuntu-latest
        steps:
            - name: 📚 checkout
              uses: actions/checkout@v2.1.1
            - name: 💥 node
              uses: actions/setup-node@v1.4.2
              with:
                  node-version: 12
                  registry-url: https://registry.npmjs.org
            - name: 🚀 publish ui
              run: npm publish --access public
              working-directory: ui
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
            - name: 🚀 publish extension
              run: npm publish --access public
              working-directory: app-extension
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}